apiVersion: audit.k8s.io/v1
kind: Policy
metadata:
  name: container-security-audit-policy
rules:
  - level: RequestResponse
    verbs: ["create", "update"]
    resources:
      - group: ""
        resources: ["pods"]
    namespaces: ["audit-zone"]
    omitStages:
      - RequestReceived
  - level: Metadata
    verbs: ["create", "update"]
    resources:
      - group: ""
        resources: ["pods"]
    namespaces: ["audit-zone"]
  - level: None
    verbs: ["get", "list", "watch", "delete"]
    resources:
      - group: ""
        resources: ["pods"]
